version: '3.9'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-safepay_db}
      POSTGRES_USER: ${DB_USER:-safepay}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-safepay}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  postgres_data:
